# ChunkCooker configuration
#
chunks-per-period: 100
seconds-per-period: 30
minimum-cycle-time: 3600
storm-on-empty-world: true
world-env: [ NORMAL ]
chunk-tick-interval: 1
verbose: false

worlds:
  SomeRandomWorld:
    chunks-per-period: 100
    seconds-per-period: 30
    storm-on-empty-world: true
    minimum-cycle-time: 3600
     